version: 0.1
repos:
  - group: oclif-core
    github_org: oclif
    repos:
      - config
      - command
      - errors
      - parser
  - group: oclif-plugins
    github_org: oclif
    repos:
      - plugin-autocomplete
      - plugin-commands
      - plugin-command-snapshot
      - plugin-help
      - plugin-interceptor
      - plugin-legacy
      - plugin-not-found
      - plugin-plugins
      - plugin-update
      - plugin-warn-if-update-available
      - plugin-which
  - group: oclif-utils
    github_org: oclif
    repos:
      - screen
      - color
      - node-linewrap
      - cli-ux
      - test
      - fancy-test
      - fancy-test-nock
      - oclif
      - dev-cli
      - tslint
      - eslint
      - eslint-config-oclif
      - eslint-config-oclif-typescript
      - nyc-config
      - docker
      - semantic-release
sequences:
  add-dependabot:
    description: 'chore: add dependabot.yml'
    assertions:
      - type: file-is-exact
        description: 'add dependabot.yml to github dir'
        target_relative_filepath: .github/dependabot.yml
        source_relative_filepath: workflows/2020-06-23-add-dependabot/dependabot.yml
        if: ls yarn.lock
  pin-typescript:
    description: 'chore: pin typescript'
    assertions:
      - type: node-project-has-deps
        description: pin typescript
        manager: yarn
        dev_dependencies:
          - "typescript@3.8.3"
        if: "cat package.json | grep \\\"typescript\\\""

workflows:
  github-ci:
    apply_to_groups:
      - oclif-core
      - oclif-plugins
      - oclif-utils
    sequences:
      - add-dependabot
      - pin-typescript
