---
version: 2
jobs:
  assert: &assert
    docker:
      - image: node:latest
    working_directory: ~/leif
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run leif
          command: |
            rm ~/.gitconfig
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_USERNAME"
            npx leif --version
            npx leif run cron/leif.yml
  dry-run:
    <<: *assert
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run leif in dry-run mode
          command: |
            rm ~/.gitconfig
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "$GIT_USERNAME"
            npx leif --version
            npx leif run cron/leif.yml -d

workflows:
  version: 2
  "oclif-leif":
    jobs:
      - assert:
          context: SF-CLI-RELEASE-PROCESS
          filters:
            branches:
              only:
                - main
      - dry-run:
          context: SF-CLI-RELEASE-PROCESS
          filters:
            branches:
              ignore:
                - main
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - assert:
          context: SF-CLI-RELEASE-PROCESS
