---
version: 2
jobs:
  assert: &assert
    docker:
      - image: node:latest
    working_directory: ~/leif
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run leif
          command: |
            rm ~/.gitconfig
            npx leif run cron/dependabot/leif.yml
  dry-run:
    <<: *assert
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run leif in dry-run mode
          command: |
            rm ~/.gitconfig
            npx leif run cron/dependabot/leif.yml -d

workflows:
  version: 2
  "oclif-leif":
    jobs:
      - assert:
          context: org-global
          filters:
            branches:
              only:
                - master
      - dry-run:
          context: org-global
          filters:
            branches:
              ignore:
                - master
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - assert:
          context: org-global
