version: 0.1
repos:
  - group: oclif-core
    github_org: oclif
    repos:
      - config
      - command
      - errors
      - parser
  - group: oclif-plugins
    github_org: oclif
    repos:
      - plugin-autocomplete
      - plugin-commands
      - plugin-command-snapshot
      - plugin-help
      - plugin-interceptor
      - plugin-legacy
      - plugin-not-found
      - plugin-plugins
      - plugin-update
      - plugin-warn-if-update-available
      - plugin-which
  - group: oclif-utils
    github_org: oclif
    repos:
      - screen
      - color
      # - node-linewrap
      - cli-ux
      - test
      - fancy-test
      - fancy-test-nock
      - oclif
      - dev-cli
      - eslint
      - eslint-config-oclif
      - eslint-config-oclif-typescript
      - nyc-config
      # - docker
      - semantic-release
sequences:
  sync-dependabot:
    description: 'chore: sync dependabot.yml'
    assertions:
      - type: file-is-exact
        description: 'chore: sync dependabot.yml'
        target_relative_filepath: .github/dependabot.yml
        source_relative_filepath: cron/dependabot/dependabot.yml

workflows:
  sync-dependabot:
    apply_to_groups:
      - oclif-core
      - oclif-plugins
      - oclif-utils
    sequences:
      - sync-dependabot
